### ISSUE TITLE
Not all installed Apps are displayed

### ISSUE THREAD

**Issue by xxpasixx** [gfwilliams/Gadgetbridge#2] opened 2022-06-10 14:04 UTC
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [Codeberg Terms of Use](https://codeberg.org/codeberg/org/src/branch/master/TermsOfUse.md)

### I got Gadgetbridge from:
* [x] Playstore (Bangle.js Version)

#### Your issue is:
*If possible, please attach [logs](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*

<details>
  <summary>Click to see my log under this fold</summary>

```
15:48:50.629 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 15:48:50: Transaction task: onDeleteNotification with 2 actions
15:48:50.631 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 10. Juni, 15:48: WriteAction on characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e
15:48:50.632 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e: 0x10 0x47 0x42 0x28 0x7b 0x74 0x3a 0x22 0x6e 0x6f 0x74 0x69 0x66 0x79 0x2d 0x22 0x2c 0x69 0x64 0x3a
15:48:50.634 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 6e400002-b5a3-f393-e0a9-e50e24dcca9e (success)
15:48:50.635 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 10. Juni, 15:48: WriteAction on characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e
15:48:50.637 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e: 0x31 0x36 0x35 0x34 0x38 0x36 0x37 0x32 0x34 0x32 0x7d 0x29 0x0a
15:48:50.639 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 6e400002-b5a3-f393-e0a9-e50e24dcca9e (success)
15:48:50.932 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 6e400003-b5a3-f393-e0a9-e50e24dcca9e value: 0x42 0x4c 0x45 0x20 0x43 0x6f 0x6e 0x6e 0x65 0x63 0x74 0x65 0x64 0x2c 0x20 0x71 0x75 0x65 0x75 0x65
15:48:50.932 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - RX: BLE Connected, queue
15:48:50.943 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 6e400003-b5a3-f393-e0a9-e50e24dcca9e value: 0x69 0x6e 0x67 0x20 0x42 0x4c 0x45 0x20 0x72 0x65 0x73 0x74 0x61 0x72 0x74 0x20 0x66 0x6f 0x72 0x20
15:48:50.944 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - RX: ing BLE restart for 
15:48:50.954 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 6e400003-b5a3-f393-e0a9-e50e24dcca9e value: 0x6c 0x61 0x74 0x65 0x72 0x0d 0x0a
15:48:50.954 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - RX: later

15:48:50.955 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - UART RX LINE: >BLE Connected, queueing BLE restart for later
15:48:50.955 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - UART RX line started with 62 - ignoring
15:48:51.011 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 6e400003-b5a3-f393-e0a9-e50e24dcca9e value: 0x42 0x4c 0x45 0x20 0x43 0x6f 0x6e 0x6e 0x65 0x63 0x74 0x65 0x64 0x2c 0x20 0x71 0x75 0x65 0x75 0x65
15:48:51.011 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - RX: BLE Connected, queue
15:48:51.023 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 6e400003-b5a3-f393-e0a9-e50e24dcca9e value: 0x69 0x6e 0x67 0x20 0x42 0x4c 0x45 0x20 0x72 0x65 0x73 0x74 0x61 0x72 0x74 0x20 0x66 0x6f 0x72 0x20
15:48:51.023 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - RX: ing BLE restart for 
15:48:51.033 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 6e400003-b5a3-f393-e0a9-e50e24dcca9e value: 0x6c 0x61 0x74 0x65 0x72 0x0d 0x0a
15:48:51.034 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - RX: later

15:48:51.034 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - UART RX LINE: BLE Connected, queueing BLE restart for later
15:48:51.034 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - UART RX line started with 66 - ignoring
15:48:53.806 [main] DEBUG n.f.g.e.NotificationListener - Notification posted: com.android.systemui: sys
15:48:53.807 [main] DEBUG n.f.g.e.NotificationListener - notificationAppListIsBlackList: true
15:48:53.810 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
15:48:53.811 [main] DEBUG n.f.g.e.NotificationListener - Ignoring notification source
15:49:13.862 [main] DEBUG n.f.g.e.NotificationListener - Notification posted: com.android.systemui: sys
15:49:13.864 [main] DEBUG n.f.g.e.NotificationListener - notificationAppListIsBlackList: true
15:49:13.866 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
15:49:13.867 [main] DEBUG n.f.g.e.NotificationListener - Ignoring notification source
15:49:33.458 [main] DEBUG n.f.g.e.NotificationListener - Notification posted: com.instagram.android: msg
15:49:33.459 [main] DEBUG n.f.g.e.NotificationListener - notificationAppListIsBlackList: true
15:49:33.478 [main] INFO  n.f.g.e.NotificationListener - Processing notification 1654867245 age: 715 from source com.instagram.android with flags: 17
15:49:33.488 [main] DEBUG n.f.g.e.NotificationListener - No Notification Filter found
15:49:33.495 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
15:49:33.498 [main] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - UART TX: GB({t:"notify",id:1654867245,title:"changed Title",body:"test"})

15:49:33.499 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 15:49:33: Transaction task: onNotification with 5 actions
15:49:33.501 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 10. Juni, 15:49: WriteAction on characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e
15:49:33.503 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e: 0x10 0x47 0x42 0x28 0x7b 0x74 0x3a 0x22 0x6e 0x6f 0x74 0x69 0x66 0x79 0x22 0x2c 0x69 0x64 0x3a 0x31
15:49:33.509 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 6e400002-b5a3-f393-e0a9-e50e24dcca9e (success)
15:49:33.510 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 10. Juni, 15:49: WriteAction on characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e
15:49:33.512 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e: 0x36 0x35 0x34 0x38 0x36 0x37 0x32 0x34 0x35 0x2c 0x74 0x69 0x74 0x6c 0x65 0x3a 0x22 0x70 0x61 0x6d
15:49:33.514 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 6e400002-b5a3-f393-e0a9-e50e24dcca9e (success)
15:49:33.515 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 10. Juni, 15:49: WriteAction on characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e
15:49:33.517 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e: 0x20 0x4c 0x69 0x67 0x68 0x74 0x73 0x22 0x2c 0x62 0x6f 0x64 0x79 0x3a 0x22 0x28 0x78 0x78 0x5f 0x70
15:49:33.519 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 6e400002-b5a3-f393-e0a9-e50e24dcca9e (success)
15:49:33.520 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 10. Juni, 15:49: WriteAction on characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e
15:49:33.522 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e: 0x61 0x73 0x69 0x78 0x78 0x29 0x3a 0x20 0x70 0x61 0x6d 0x6c 0x69 0x67 0x68 0x74 0x73 0x64 0x65 0x3a
15:49:33.524 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 6e400002-b5a3-f393-e0a9-e50e24dcca9e (success)
15:49:33.526 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 10. Juni, 15:49: WriteAction on characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e
15:49:33.527 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e: 0x20 0x74 0x65 0x73 0x74 0x22 0x7d 0x29 0x0a
15:49:33.530 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 6e400002-b5a3-f393-e0a9-e50e24dcca9e (success)
15:49:33.956 [main] DEBUG n.f.g.e.NotificationListener - Notification posted: com.android.systemui: sys
15:49:33.956 [main] DEBUG n.f.g.e.NotificationListener - notificationAppListIsBlackList: true
15:49:33.963 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
15:49:33.964 [main] DEBUG n.f.g.e.NotificationListener - Ignoring notification source
15:49:34.348 [Binder:12981_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 6e400003-b5a3-f393-e0a9-e50e24dcca9e value: 0x42 0x4c 0x45 0x20 0x43 0x6f 0x6e 0x6e 0x65 0x63 0x74 0x65 0x64 0x2c 0x20 0x71 0x75 0x65 0x75 0x65
15:49:34.349 [Binder:12981_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - RX: BLE Connected, queue
```
</details>

#### Your wearable device is:

Bangle js 2 v14

#### Your Android version/manufacturer flavor is: 
Samsung Galaxy A50, Android 11

#### Gadgetbridge Version
0.67.1a-banglejs
Commit 6fb22b944

When installing the Bangle.js Gadgetbridge app from the Playstore, the list of all Apps does not contain all Apps. (feels like only the default installed one.)
i gave the app every permission i could find in the Android settings.

Incoming notifications from Apps that are not listed are always shown, but does not have the right icons. The absent of the notification is then allways "messages"

After a few days, some of the Apps are available in the list. Mainly these apps with a lot of notifications triggerd.

I don't have any idea why this could be the case or how to solve it, but i would like to get this out of the long discussion from the forum: http://forum.espruino.com/conversations/370708/

**Comment by idavydov** [comment] 2022-06-10 14:52
I am having the same issue. Previously, I was using vanilla gadgetbridge and I saw all the apps.

I checked permissions. Specifically, I enabled all app permission in app info and allowed notification access. Also disabled battery optimization, but that's probably unrelated. Any other permissions I could check?

**Comment by myxor** [comment] 2022-06-11 16:02
I can confirm the same issue running LineageOS 18.1 / Android 11.

**Comment by gfwilliams** [comment] 2022-06-14 08:41
Ok, just to be clear we're talking about **Android Apps** in `Notification settings` -> `Applications list`?

> After a few days, some of the Apps are available in the list. Mainly these apps with a lot of notifications triggerd.

Is it possible that the apps only get shown in that list when they actually create a notification?

I guess I'm wondering whether the normal Gadgetbridge works exactly the same way, but that you just didn't notice because by the time you'd looked in the menu, enough apps had created notifications?

**Comment by johan-m-o** [comment] 2022-06-14 09:00
> Ok, just to be clear we're talking about **Android Apps** in `Notification settings` -> `Applications list`?

Yup.

> Is it possible that the apps only get shown in that list when they actually create a notification?

I'm missing many apps in the list that regularly create notifications.

> I guess I'm wondering whether the normal Gadgetbridge works exactly the same way, but that you just didn't notice because by the time you'd looked in the menu, enough apps had created notifications?

As far as I remember the list in the regular Gadgetbridge app is complete and shows all apps on the device, even without them having created any notifications. I could do a clean install of the normal Gadgetbrigde app and confirm if you want, but I'm pretty sure that was the case.

I've seen talk that this might be a permissions issue, and if so it might be related to another problem I've seen with the Bangle.js Gadgetbrigde: it doesn't ask for permissions on first start. The regular app does this without problems, but with the Bangle.js app I (and I've seen others report the same) need to go into Android settings and enable all the permissions manually. I'll open a separate issue for that soon.

**Comment by gfwilliams** [comment] 2022-06-14 09:33
> it doesn't ask for permissions on first start. 

Does it pop up a dialog saying it's *going* to ask? That's something I had to add specifically for the Play Store, and I just tested and it seems to work ok here.

Specifically you get sent to somewhere where you have to give it `Notification Access` and then it shows a danger sign and makes you wait 10 seconds before you can click `Yes`

**Comment by johan-m-o** [comment] 2022-06-14 09:37
> > it doesn't ask for permissions on first start.
> 
> Does it pop up a dialog saying it's _going_ to ask? That's something I had to add specifically for the Play Store, and I just tested and it seems to work ok here.
> 
> Specifically you get sent to somewhere where you have to give it `Notification Access` and then it shows a danger sign and makes you wait 10 seconds before you can click `Yes`

Yes, giving notification access works as it should. It's just all the regular Android permissions (Calendar, call logs, etc) that aren't asked for on the Bangle.js app but works without issue on the regular GB app.

**Comment by gfwilliams** [comment] 2022-06-14 09:46
> It's just all the regular Android permissions (Calendar, call logs, etc) that aren't asked for on the Bangle.js app

Do you still get a dialog asking you? But just when you click 'ok' nothing happens?

**Comment by johan-m-o** [comment] 2022-06-14 10:40
> > It's just all the regular Android permissions (Calendar, call logs, etc) that aren't asked for on the Bangle.js app
> 
> Do you still get a dialog asking you? But just when you click 'ok' nothing happens?

No dialog at all.

**Comment by gfwilliams** [comment] 2022-06-14 10:55
Ok, well that's interesting then. It'd be really helpful if you or someone else who has this issue could try and step through the code in ControlCenterv2 (specifically checkAndRequestPermissions) and try and figure out what's going wrong then, because this works for me.

In my case, it all seems fine *however* after I click Ok on the dialog, `ActivityCompat.requestPermissions` is called (with it seems all the right stuff), but it *doesn't* pop up a dialog allowing me to grant permission - it just silently completes. Not sure if that's my phone or not.

... but if you don't get a dialog it's either because it's not the first time you started, or somehow Gadgetbridge thinks it already has all the permissions it needs

**Comment by gfwilliams** [comment] 2022-06-15 07:44
Just noticed something odd here too. I wasn't getting `src` set up on notifications, and debugging it I see things like: `android.content.pm.PackageManager$NameNotFoundException: com.google.android.talk`

Looks suspiciously like the change from SDK 29 to SDK 30 might be the issue: https://stackoverflow.com/questions/34709873/packagemanager-namenotfoundexception/69925975#69925975

I'd stupidly thought that just bumping the SDK was fine but it seems it breaks it! I'll see if I can push a new build that uses SDK 29

**Comment by gfwilliams** [comment] 2022-06-15 08:01
Well this sucks. Looks like I *have* to submit to the play store with SDK 30 :( However I can request QUERY_ALL_PACKAGES permission which seems to fix this. I'll try and get this in the next release

**Comment by gfwilliams** [comment] 2022-06-15 11:55
Ok, 0.67.1b-banglejs is now rolled out so should update on Google Play soon.

Pretty sure this is fixed now, but please reopen if it's not :)

**Closed as completed by gfwilliams** 2022-06-15 11:55 UTC

**Comment by johan-m-o** [comment] 2022-06-15 12:20
Can confirm that 0.67.1b-banglejs shows all installed apps.
